### ISSUE TITLE
can you specify how can upload sound to soundcloud

### ISSUE THREAD

**Issue by divsbhalala** [vineetasharma/soundcloud-node-api#2]
can you specify how can upload sound to soundcloud using your API i ma using below code 
`SoundCloud.post('/tracks', {
                                                'track[title]': 'testtitle',
                                                'track[description]': 'podcast',
                                                'track[downloadable]': true,
                                                'track[track_type]': 'podcast',
                                                'oauth_token': obj.__data.dest.token,
                                                'track[asset_data]': '@' + data
                                            })`

and getting error like this http://i.prntscr.com/107fcc0d75c04ade9b21966186bb6cd0.png

**Comment by vineetasharma** [comment]
@divsbhalala Currently this module supports only get request no post requests are implemented yet. But I am planning to implement it.
